### ISSUE TITLE
Should not include -Zshare-generics for non-nightly projects

### ISSUE THREAD

**Issue by paul-hansen** [TimJentzsch/cargo-bavy#10]
Creating a project with nightly toolchain disabled and fast linker enabled causes this error when running the project:
```
error: the option `Z` is only accepted on the nightly compiler
```

If the nightly toolchain is not selected, `rustflags = ["-Zshare-generics=n"]` should not be added to the `.cargo/config.toml` file as it is a nightly only feature.

P.S. I was just thinking the other night about making something like this, thanks for making it!

**Comment by TimJentzsch** [comment]
Ahh, good catch! I removed the `"-Zshare-generics=y"` entries, but forgot about this one
